name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  auth-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Check if auth-service exists
        run: |
          if [ ! -f "./devops-microservices-pipeline/services/auth-service/requirements.txt" ]; then
            echo "Auth service not found."
            exit 1
          fi

      - name: Install Python dependencies
        working-directory: ./services/auth-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
